export const ColorsDark = {
  PRIMARY_MAIN: '#1F2630',
  PRIMARY_HOVER: '#29313C',
  TEXT_MAIN: '#FFFF',
  TEXT_INACTIVE: '#717A8A',
  PRIMARY_BUTTON: '#FCD434',
  PRIMARY_DISABLED: '#717A8A',
  PRIMARY_CURSOR: '#F1B90C',
  PRIMARY_TEXT: '#7f8794',
  TEXTINPUT_MAIN: '#29313C',
  BOTTOM_PRIMARY: '#EBECF0',
  BOTTOM_PRIMARY_DISABLE: '#70798B',
};

export const ColorsLight = {
  PRIMARY_MAIN: '#FFFF',
  PRIMARY_HOVER: '#FAFAFA',
  TEXT_MAIN: '#1F2630',
  TEXT_INACTIVE: '#FFFF',
  PRIMARY_BUTTON: '#FCD434',
  TEXTINPUT_MAIN: '#F5f5f5',
  BOTTOM_PRIMARY: '#1F2630',
  BOTTOM_PRIMARY_DISABLE: '#AAB1BA',
};
